### ISSUE TITLE
Conda

### ISSUE THREAD

**Issue by Denisevi4** [dmlc/treelite#41]
Hi, 

Could you add treelite to conda? Thanks!

**Comment by canglangshushu** [comment]
+1

**Comment by aishgrt1** [comment]
+1

**Comment by jkokatjuhha** [comment]
+1

**Comment by IoannisZempe** [comment]
+ 1

**Comment by teju85** [comment]
+1

**Comment by canonizer** [comment]
+1

**Comment by canonizer** [comment]
@hcho3 How hard would it actually be to provide a conda installer for treelite?
@teju85 @dantegd FYI.

**Comment by hcho3** [comment]
@canonizer I'm currently working on 1.0 release for PyPI. What is your use case for using Conda specifically?

**Comment by trivialfis** [comment]
Most rapids AI components don't support PyPI due to c++14

**Comment by hcho3** [comment]
I have no prior experience setting up a conda recipe. I wonder how difficult it is.

**Comment by jakirkham** [comment]
Would suggest adding this to [conda-forge]( https://conda-forge.org ). Should add I'm biased as I work on the project. That said, conda-forge has become the defacto community Conda channel. It is also used to build packages in the Anaconda distribution. Many other domain specific channels (like `rapidsai`) use conda-forge as their base.

When it comes to contributing a new recipe, we have [a quickstart for contributing]( https://conda-forge.org/#add_recipe ) and [a FAQ]( https://github.com/conda-forge/staged-recipes#faq ). For more comprehensive information [conda-forge has docs]( https://conda-forge.org/docs/ ) and [conda-build has even more docs]( https://conda.io/projects/conda-build/en/latest/index.html ). Plus there is [an active Gitter channel]( https://gitter.im/conda-forge/conda-forge.github.io ) and there are GitHub teams like the `staged-recipes` team designed to walk you through the process.

Please let me know if you have any questions. 😄

**Comment by pidefrem** [comment]
@hcho3 the process is the following (based on https://conda-forge.org/#add_recipe):
- fork the repository https://github.com/conda-forge/staged-recipes
- create `treelite` folder in `recipes`
- create `meta.yaml` with the package description and dependencies
- create `build.sh` and `bld.bat` to build on unix and windows.

Here is an attempt of conda-build: https://github.com/conda-forge/staged-recipes/pull/11338.

These are some remarks:
- the tar.gz archive for release 0.32 is missing `dmlc-core` source so I had to use git_url instead of source tag in the `meta.yaml`
- openmp support in conda is explained here: https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp

**Comment by hcho3** [comment]
I submitted a Conda recipe to conda-forge today: https://github.com/conda-forge/staged-recipes/pull/11926.

**Comment by hcho3** [comment]
The Conda package is available now: https://anaconda.org/conda-forge/treelite
